### ISSUE TITLE
Actualize GitLab CI workflow file 

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#108]
- [x] actualize https://github.com/metanorma/ci/blob/main/cimas-config/gh-actions/samples/.gitlab-ci.yml
 - [x] review GitLab CI best practices, to simplify usage of it by other users
 - [x] test on some GitLab repository

**Comment by ronaldtse** [comment]
It seems that Inkscape does not work in the GitLab runner.

```
Metanorma XML Syntax: (XML Line 003052:64): attribute "metadata" not allowed here; expected attribute "columns", "keep-lines-together", "keep-with-next", "key", "multilingual-rendering" or "tag"
Metanorma XML Syntax: (XML Line 003114:101): element "table" not allowed here; expected element "author", "p" or "source"
Metanorma XML Syntax: (XML Line 003123:51): element "table" not allowed here; expected element "author", "p" or "source"
Metanorma XML Syntax: (XML Line 003132:51): element "table" not allowed here; expected element "author", "p" or "source"
Metanorma XML Syntax: (XML Line 003143:51): element "table" not allowed here; expected element "author", "p" or "source"
Metanorma XML Syntax: (XML Line 003153:9): element "quote" incomplete; missing required element "p"
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:150): CRITICAL **: 04:37:33.963: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:150): CRITICAL **: 04:37:33.964: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:150): CRITICAL **: 04:37:33.964: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:150): WARNING **: 04:37:34.503: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:164): CRITICAL **: 04:37:34.863: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:164): CRITICAL **: 04:37:34.864: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:164): CRITICAL **: 04:37:34.864: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:164): WARNING **: 04:37:35.023: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:178): CRITICAL **: 04:37:35.268: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:178): CRITICAL **: 04:37:35.268: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:178): CRITICAL **: 04:37:35.268: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:178): WARNING **: 04:37:35.425: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:192): CRITICAL **: 04:37:35.665: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:192): CRITICAL **: 04:37:35.665: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:192): CRITICAL **: 04:37:35.665: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:192): WARNING **: 04:37:35.820: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:206): CRITICAL **: 04:37:36.023: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:206): CRITICAL **: 04:37:36.023: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:206): CRITICAL **: 04:37:36.023: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:206): WARNING **: 04:37:36.182: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
Unable to init server: Could not connect: Connection refused
Failed to get connection
** (inkscape:220): CRITICAL **: 04:37:36.394: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:220): CRITICAL **: 04:37:36.394: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:220): CRITICAL **: 04:37:36.394: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed

** (inkscape:220): WARNING **: 04:37:36.551: Fonts dir '/usr/share/inkscape/fonts' does not exist and will be ignored.
java -Xss5m -Xmx2048m -Djava.awt.headless=true -Duser.home=/root -jar /usr/local/bundle/gems/mn2pdf-1.68/lib/../bin/mn2pdf.jar --xml-file "/tmp/document20230426-12-i718mh.xml" --xsl-file "/usr/local/bundle/gems/metanorma-ogc-2.3.8/lib/isodoc/ogc/ogc.best-practice.xsl" --pdf-file "/builds/ogc/muddi-swg/_site/documents/best_practice_on_conceptual_modeling/document.pdf" --param baseassetpath="/builds/ogc/muddi-swg/best_practice_on_conceptual_modeling" --syntax-highlight  --font-manifest "/tmp/fontist_locations20230426-12-a9v1vi.yml"
[info]: Compiling /builds/ogc/muddi-swg/conformance_of_muddi_cm_to_mds/document.adoc ...
[relaton] Sparx Systems Enterprise Architect does not have a recognised prefix
[relaton] Sparx Systems Enterprise Architect does not have a recognised prefix
Style: Submitting Organizations is missing!
Style: Executive Summary required for Engineering Reports!
Metanorma XML Style Warning: (XML Line 000030): Table should have title
Metanorma XML Style Warning: (XML Line 000092): Table should have title
Metanorma XML Syntax: (XML Line 000074:104): element "clause" not allowed here; expected the element end-tag or element "submitters"
```

This is the `.gitlab-ci.yml` file I'm using:

```yaml
image:
  name: metanorma/metanorma
  entrypoint: [ "" ]

cache:
  paths:
    - relaton/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - bundle install
    - metanorma site generate --agree-to-terms
  artifacts:
    expose_as: 'site'
    paths:
      - _site

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - |
      curl --location \
        --output artifacts.zip \
        --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        "https://gitlab.ogc.org/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_TOKEN/artifacts"
    - unzip artifacts.zip
    - mv _site public

  artifacts:
    paths:
      - public
  only:
    - master
```
